ASFLAGS_ADDITIONAL = 
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = D:/AppData/MathWorks/MATLAB Add-Ons/Toolboxes/NXP_MBDToolbox_S32K3/mbdtbx_s32k3/codertarget/2024b
STACK_SIZE = 64
